USE ECommerceDB;
GO

-- Level 2 — Joins & Analytical Thinking
-- 6. INNER JOIN
-- Return:
-- customer_name
-- order_id
-- order_date
-- amount
-- for every customer who has placed an order.

SELECT c.customer_name, o.order_id, o.order_date, o.amount
FROM customers c
    INNER JOIN orders o ON c.customer_id = o.customer_id;

-- 7. LEFT JOIN
-- Find customers who have never placed an order.
-- This is an extremely important Data Analyst interview pattern.

SELECT c.customer_name, o.order_id, o.order_date, o.amount
FROM customers c
    LEFT JOIN orders o ON c.customer_id = o.customer_id
WHERE
    o.customer_id IS NULL;

-- 8. Revenue by city
-- Calculate total revenue generated by customers from each city.
-- You'll need:
-- customers → orders

SELECT c.city, SUM(o.amount) AS total_revenue
FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
WHERE
    o.status = 'Completed'
GROUP BY
    c.city;

-- 9. Product revenue
-- Calculate revenue generated by each product.
-- You'll need:
-- products
-- ↓
-- order_items
-- ↓
-- orders
-- Revenue:
-- quantity × product price

SELECT p.product_id, p.product_name, SUM(p.price * o_i.quantity) AS total_revenue
FROM
    products p
    JOIN order_items o_i ON p.product_id = o_i.product_id
    JOIN orders o ON o_i.order_id = o.order_id
WHERE
    o.status = 'Completed'
GROUP BY
    p.product_id,
    p.product_name;

-- 10. Top customers
-- Find the top 5 customers by total spending.
-- Use:
-- TOP
-- first.
-- Then solve the same problem using:
-- ROW_NUMBER()

SELECT
    customer_id,
    customer_name,
    total_spending,
    customer_rank
FROM (
        SELECT
            c.customer_id, c.customer_name, SUM(o.amount) AS total_spending, ROW_NUMBER() OVER (
                ORDER BY SUM(o.amount) DESC
            ) AS customer_rank
        FROM customers c
            JOIN orders o ON c.customer_id = o.customer_id
        WHERE
            o.status = 'Completed'
        GROUP BY
            c.customer_id, c.customer_name
    ) AS ranked_customers
WHERE
    customer_rank <= 5
ORDER BY customer_rank;